# Generated by Django 5.1.3 on 2024-12-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(default=0, max_length=100)),
                ('main_viewpoint', models.CharField(default=0, max_length=50)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('duration', models.PositiveIntegerField(default=0, help_text='Duration in days')),
                ('media_gallery', models.ImageField(blank=True, default=0, null=True, upload_to='packages/media_gallery/')),
            ],
        ),
    ]
