# Generated by Django 5.1.3 on 2024-12-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_package_media_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in days'),
        ),
        migrations.AlterField(
            model_name='package',
            name='main_viewpoint',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='package',
            name='media_gallery',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='gallry/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='place',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
