# Generated by Django 5.1.3 on 2024-12-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_package_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
